### PR TITLE
Update to Rails 4.1.16

### PR DESCRIPTION
**Pull request by rawburt**
Using `ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-darwin15]` ...

When running the tests there would be many `Undefined method 'year' for nil:NilClass` errors. This error came from the code in `WithGameWeek.start_of_first_gameweek` specifically the line `Time.zone.parse(Settings.first_gameweek_start)`. Exploring the internet it seemed to be a bug with Rails. Updating to the latest 4.1.x version of Rails resolved the issue.

### CODE REVIEW

**Comment by rawburt** [comment]
In response to the CI error: you might need to update the CI commands to run `env RAILS_ENV=test bundle exec rake db:migrate`, or some equivalent, before running the tests...maybe 😄

**Comment by ishakir** [comment]
Hi rawburt,

Thanks for sending this over! Hopefully I'll have time to look at the build failure over the weekend. If you're keen to get this merged earlier, you can have a go yourself! Everything is run through travis (configured via .travis.yml at the top level),.

Regards,
Imran

**Comment by rawburt** [comment]
@ishakir Awesome, I'll poke around a bit, then!

**Comment by rawburt** [comment]
Cool, I think I fixed it all up :shipit:

**Pull request merged**
